services:
  homeflix:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./data:/data"
    networks:
      - proxynet
  chromedriver:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - proxynet
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

networks:
  proxynet:
    name: custom_network
