name: Release homeflix.io

on:
  push:
    tags:
      - '*'

env:
  AUTH_TOKENS: ${{ secrets.AUTH_TOKENS }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Tag
        run: |
          echo $GITHUB_REF_NAME
          echo $GITHUB_REF
      - name: Write Secrets
        run: |
          echo "${AUTH_TOKENS}" > ./api/auth.json
      - name: Build image
        run: |
          docker build -t homeflix.io .
      - name: Tag image
        run: |
          if [[ $GITHUB_REF_NAME =~ pre ]];
          then
              echo "Version is a pre-release, adding beta tag"
              docker tag homeflix.io douglasoconnor/homeflix.io:beta
          else
              echo "Version is a production release, adding latest tag"
              docker tag homeflix.io douglasoconnor/homeflix.io:latest
          fi
          docker tag homeflix.io douglasoconnor/homeflix.io:$GITHUB_REF_NAME
          docker login -u douglasoconnor -p $DOCKER_ACCESS_TOKEN
      - name: Push Image
        run: |
          if [[ $GITHUB_REF_NAME =~ pre ]];
          then
              docker push douglasoconnor/homeflix.io:$GITHUB_REF_NAME
              docker push douglasoconnor/homeflix.io:beta
          else
              docker push douglasoconnor/homeflix.io:$GITHUB_REF_NAME
              docker push douglasoconnor/homeflix.io:latest
          fi
      