name: Sync README to DockerHub

on:
  push:
    main

env:
  AUTH_TOKENS: ${{ secrets.AUTH_TOKENS }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

jobs:
  build:
    name: Sync README
    runs-on: ubuntu-latest
    steps:
      - name: Dockerhub Readme
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: douglasoconnor
          password: $DOCKER_ACCESS_TOKEN
          repository: douglasoconnor/homeflix.io
          readme: "./README.md"