name: Sync README to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Sync README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dockerhub Readme
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: douglasoconnor
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: douglasoconnor/homeflix.io
          readme: "./README.md"