name: Run Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AUTH_TOKENS: ${{ secrets.AUTH_TOKENS }}
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

jobs:
  build:
    name: End to End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Write Secrets
        run: |
          echo "${AUTH_TOKENS}" > ./api/auth.json
      - name: Install
        run: |
          sh install.sh
      - name: Run Tests
        run: |
          nohup sh startup.sh > output.log &
          cd client
          mkdir screenshots
          export SCREEN_WIDTH=1920
          export SCREEN_HEIGHT=1080
          npm run test src/tests/e2e/*.test.js
      - name: Upload Screenshots
        run: |
          npm install --save-dev @percy/cli
          ./node_modules/.bin/percy upload screenshots